### PR TITLE
Group code objects by kernel name in perf report summary

### PR DESCRIPTION
**Pull request by pfultz2**
Bert now show a summary like this:

```
Summary:
gpu::gemm: 8.582ms, 65%
gpu::triadd_layernorm: 0.804272ms, 7%
gpu::softmax: 0.794769ms, 6%
gpu::code_object::add_kernel: 0.646121ms, 5%
gpu::code_object::mul_kernel: 0.623822ms, 5%
gpu::code_object::add_mul_erf_add_mul_mul_kernel: 0.498902ms, 4%
gpu::code_object::mul_add_kernel: 0.478352ms, 4%
gpu::contiguous: 0.333988ms, 3%
hip::hip_copy_literal: 0.162432ms, 2%
load: 0.125854ms, 1%
gpu::gather: 0.0729777ms, 1%
gpu::code_object::convert_kernel: 0.049062ms, 1%
multibroadcast: 0.044116ms, 1%
gpu::layernorm: 0.032414ms, 1%
transpose: 0.0297579ms, 1%
slice: 0.0296842ms, 1%
gpu::code_object::add_tanh_convert_kernel: 0.0249871ms, 1%
reshape: 0.0216463ms, 1%
@param: 0.00238ms, 1%
check_context::migraphx::version_1::gpu::context: 0.000734ms, 1%
hip::hip_allocate_memory: 0.00047ms, 1%
```

### CODE REVIEW

**Comment by causten** [comment]
tested on different server and prints work

**Comment by umangyadav** [comment]
> I cannot get the models to run in driver perf.
> 
> ```
> root@557fcf91b2a1:/code/2_AMDMIGraphX/docker_build# ./bin/driver perf bertsquad-10.onnx --fill1 input_ids --fill1 segment_ids --input-dim @input_ids 1 384 --fp16
> Compiling ...
> Reading: bertsquad-10.onnx
> terminate called after throwing an instance of 'migraphx::version_1::exception'
>   what():  /code/2_AMDMIGraphX/src/program.cpp:171: compile: Dangling reference in module main from instruction 998
> Aborted (core dumped)
> ```
@CharlieL7 
Maybe same as this issue #1230

**Comment by causten** [comment]
#1230  was fixed with https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1233.  And that's merged

**Comment by causten** [comment]
I too am seeing a Dangling reference problem, but it is in the develop branch, not this PR.  I ran 
/opt/rocm/bin/migraphx-driver perf --model resnet50 
with success.

**Review by CharlieL7 — APPROVED** [review]

**Pull request merged**
