### PR TITLE
Fix MLIR input fusion non-std shapes from squeeze, flatten and unsqueeze

### PR DESCRIPTION
**Pull request by manupak**
Currently, we see MLIR partition candidates recieving non-standard shape due to not fusing in squeeze, flatten and unsqueeze ops. These ops could be canonicalized to reshape without introducing additional ops as long as MLIR backend is concerned.

### CODE REVIEW

**Review by krzysz00 — APPROVED** [review]
This seems fine to me, but I want to confirm that squeeze, unsqueeze, and flatten can all be replaced by `reshape` correctly like this

Also, can you add a test?

**Review by giuseros — APPROVED** [review]
I can confirm that the tests are passing on mi200: http://rocmhead.amd.com:8080/blue/organizations/jenkins/MLIR%2Ftest/detail/test/30/pipeline/54

**Comment by manupak** [comment]
> This seems fine to me, but I want to confirm that squeeze, unsqueeze, and flatten can all be replaced by `reshape` correctly like this
> 
> Also, can you add a test?

They are special cases of 'reshape' where as in reshape just work all that out by just knowing the output shape.

I ve added tests now.

**Review by pfultz2 — APPROVED** [review]
In the future, it would be to make these transformation when we are generating MLIR.

**Pull request merged**
