### PR TITLE
Fix HIP-Clang GPU build issues

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Add missing device attributes for GPU functions. GPU functions must be annotated with __device__ in HIP. Also, fix a few warning: nvcc does not allow '__device__' to appear after '()' in lambdas. Add __device__ for add_unary as well.

**Test Results on HIP-Clang:**
99% tests passed, 2 tests failed out of 191

Total Test time (real) =  30.74 sec

The following tests FAILED:
         37 - test_gpu_ops_test (OTHER_FAULT)
        191 - test_py_array (Failed)
Errors while running CTest

### CODE REVIEW

**Comment by pfultz2** [comment]
Can you fix these warning from cppcheck?

```
/var/jenkins/workspace/_AMDMIGraphX_hip-clang-build-fix/src/targets/gpu/device/add.cpp:11:0: warning: Attributes to lambdas must come after parameter list. [LambdaAttribute]
```

There's a lot of them. I think it because you put `__device__` before the parameter list in the lambdas. 

>  nvcc does not allow 'device' to appear after '()' in lambdas.

We dont compile for nvcc so this is not an issue.

**Comment by aaronenyeshi** [comment]
@pfultz2 I just rebased to tip, and also moved all the __device__ attribute after the parameters as you suggested. I also ran clang-format on this change too.

**Comment by aaronenyeshi** [comment]
There seems to be more cppcheck errors, but I don't see any useful output in clang tidy.

**Comment by pfultz2** [comment]
I can fix the cppcheck errors. But it seems like with this change, hip can no longer launch the kernels. It say that there is no metadata for the function.

**Comment by pfultz2** [comment]
Can you fix the merge conflicts?

**Comment by aaronenyeshi** [comment]
sorry for the delay, I lent my dev machine for testing, and they deleted all containers, including this one

**Comment by aaronenyeshi** [comment]
Do you know how to fix this bug: 
[ 15%] Building CXX object src/CMakeFiles/migraphx.dir/instruction.cpp.o
In file included from /root/AMDMIGraphX/src/eliminate_concat.cpp:2:
In file included from /root/AMDMIGraphX/src/include/migraphx/eliminate_concat.hpp:6:
In file included from /root/AMDMIGraphX/src/include/migraphx/concat_opt.hpp:11:
In file included from /root/AMDMIGraphX/src/include/migraphx/operation.hpp:12:
In file included from /root/AMDMIGraphX/src/include/migraphx/argument.hpp:4:
In file included from /root/AMDMIGraphX/src/include/migraphx/shape.hpp:11:
/root/AMDMIGraphX/src/include/migraphx/half.hpp:27:35: error: no member named 'expr' in namespace 'half_float::detail'
struct deduce<half_float::detail::expr>
              ~~~~~~~~~~~~~~~~~~~~^

**Comment by pfultz2** [comment]
> Do you know how to fix this bug:

I dont know. `expr` should always be in the `half_float::detail` namespace. How are you getting this compilation error?

**Comment by aaronenyeshi** [comment]
Should we trigger a new build?

**Pull request merged**
