### PR TITLE
Super resolution example

### PR DESCRIPTION
**Pull request by cagery**
This PR introduces super resolution example, which scales low-res image to high-res, using [sub-pixel conv layer](https://arxiv.org/abs/1609.05158).

Provides requirements file and notebook to run the example.

### CODE REVIEW

**Comment by kahmed10** [comment]
My only concern with this example is that the original image is already smaller than the input, so we are calling `resize_cover()` to first upscale the input. It would be better to start with an image that is the expected output size, downscale, then use the network to upscale. You could also possibly display the PSNR as well, but that's up to you.

**Review by kahmed10 — APPROVED** [review]

**Comment by cagery** [comment]
@kahmed10 Thanks for the suggestion!
I have added PSNR. I am making PSNR measurements on output image vs upscaled input. 
The new input image is not the expected output size but is larger than the expected input dims. 400x400. 
Let me know what you think.

**Review by turneram — APPROVED** [review]

**Review by scxiao — COMMENTED** [review]
Can you add some information like the "Steps" as that in the BERT model PR?

**Comment by cagery** [comment]
> Can you add some information like the "Steps" as that in the BERT model PR?

Just added the steps, thanks Shucai!

**Review by pfultz2 — APPROVED** [review]

**Review by scxiao — APPROVED** [review]

**Pull request merged**
