### PR TITLE
Fixed CMakeLists.txt for MLIR import

### PR DESCRIPTION
**Pull request by sjw36**
Was referencing MLIRMIOpenThin (dynamic lib). Changed to MLIRMIOpen (static lib)

### CODE REVIEW

**Comment by sjw36** [comment]
@mvermeulen  you will need this change to build with MLIR_MIOPEN_ENABLE.

**Comment by mvermeulen** [comment]
@sjw36 assume that should be MIGRAPHX_ENABLE_MLIR

**Comment by mvermeulen** [comment]
```
-- clang-offload-bundler: /opt/rocm/llvm/bin/clang-offload-bundler
-- extractkernel: 
CMake Error at src/targets/gpu/CMakeLists.txt:269 (message):
  libMLIRMIOpenThin not found
```
What is needed to build this combination or is there one I can borrow?

**Comment by sjw36** [comment]
> ```
> -- clang-offload-bundler: /opt/rocm/llvm/bin/clang-offload-bundler
> -- extractkernel: 
> CMake Error at src/targets/gpu/CMakeLists.txt:269 (message):
>   libMLIRMIOpenThin not found
> ```
> 
> What is needed to build this combination or is there one I can borrow?

If you want the dynamic lib, you can add build options in the Dockerfile(89), such as:

> RUN PATH=/opt/cmake/bin:$PATH cget -p /usr/local install ROCmSoftwarePlatform/llvm-project-mlir@02078ce236ad90e3aec04c0c770ef5bfc99e49c2 **-DBUILD_SHARED_LIBS -DLLVM_BUILD_LLVM_DYLIB**

**Comment by pfultz2** [comment]
This breaks the MLIR stage on jenkins.

**Comment by pfultz2** [comment]
With #1373 I am going to close this.

**Pull request closed without merging**
