### PR TITLE
expose underlying migraphx::argument data pointer in pybind

### PR DESCRIPTION
**Pull request by shivadbhavsar**
Add python binding for the data method of migraphx::argument class. This is required by torch_migraphx to use the underlying data for creating torch tensors.

### CODE REVIEW

**Comment by shivadbhavsar** [comment]
There is currently no use case for some of the other methods:
empty()
reshape(shape s)
copy()
share()

Do you guys think it may be worth exposing any of these through pybind as well with this change?

**Comment by umangyadav** [comment]
> There is currently no use case for some of the other methods: empty() reshape(shape s) copy() share()
> 
> Do you guys think it may be worth exposing any of these through pybind as well with this change?

I think, we should add them as and when required based on use case.

**Review by umangyadav — APPROVED** [review]

**Review by pfultz2 — APPROVED** [review]

**Comment by pfultz2** [comment]
> Do you guys think it may be worth exposing any of these through pybind as well with this change?

I dont think we will need those methods for now.

**Review by pfultz2 — CHANGES_REQUESTED** [review]
Documentation needs updated.

**Review by pfultz2 — APPROVED** [review]

**Pull request merged**
