### PR TITLE
fix tf fusion regressions

### PR DESCRIPTION
**Pull request by kahmed10**
caused by transposes left in program that made matchers not recognize fusions

### CODE REVIEW

**Comment by mvermeulen** [comment]
As noted separately in email, this seems to address the performance regression this week.  Tested with normal performance tests (minus onnx runtime tests).

**Review by scxiao — COMMENTED** [review]
do we need some unit tests for the changes?

**Comment by kahmed10** [comment]
Added unit tests

**Review by scxiao — APPROVED** [review]

**Comment by kahmed10** [comment]
Retry DeepCode

**Pull request merged**
