### PR TITLE
ASAN build excluding additional files

### PR DESCRIPTION
**Pull request by arvindcheru**
Summary of proposed changes:

- Changes for ASAN Packaging [SWDEV-398093]
- Will enable only required files for ASAN Packaging. (library and License file)

### CODE REVIEW

**Comment by pfultz2** [comment]
This should be done in rocm-cmake.

**Comment by nunnikri** [comment]
@pfultz2  thanks for taking a look at the changes. 
Agree this can be handled in rocm-cmake. But it might need more changes both in rocm-cmake and individual modules to differentiate asan instrumentable files and asan non-instrumentable files. Given the timeline and complication if you could approve the current changes it would be great. 
@frepaul

**Comment by pfultz2** [comment]
So this should be merged into the 5.7 release branch not develop branch.

**Comment by arvindcheru** [comment]
> 

Thanks for the comments, Are we waiting release 5.7 branch to be created?

**Review by umangyadav — APPROVED** [review]

**Comment by pfultz2** [comment]
I rebased this to the 5.7 branch. So this can be merged.

**Pull request merged**
