### PR TITLE
Bump MLIR picking up enhancements for upcoming release

### PR DESCRIPTION
**Pull request by causten**

### CODE REVIEW

**Review by umangyadav — APPROVED** [review]

**Comment by jerryyin** [comment]
Please hold on merging this PR until Krzysztof's hot fix related with devOp's asan error went into release branch: https://github.com/ROCmSoftwarePlatform/rocMLIR/pull/1280. Then we probably will have another commit hash instead of the current one.

**Comment by krzysz00** [comment]
https://github.com/ROCmSoftwarePlatform/rocMLIR/pull/1281 is the PR that'll land in the release
Y'all can probably just take the commit hash out of the PR, and I'll mark it `[USE MERGE COMMIT]` so that you can still use the hash of the PR commit

That is `ca060f4f434fb79a26cae3ec491b4d55e81d571a`

**Comment by jerryyin** [comment]
@krzysz00 Don't use the commit hash in the PR, use the one after the merge in the develop branch. The commit hash in the PR will get pruned away once branch is deleted.

**Comment by jerryyin** [comment]
I believe this PR is good to go. @krzysz00 managed to put 2 workarounds in that come from the last minute. 

@krzysz00 Please approve if this is last update needed from rocMLIR.

**Review by krzysz00 — APPROVED** [review]
This is the correct commit, approved

**Comment by causten** [comment]
I'm seeing a failure in CI,  `dmesg` also shows a failure at the time which leads to a amdgpu driver issuing a reset.  I'm restarting CI to determine if the failure follows the system or the run.

297/328 Test #310: test_api_custom_op_gpu ....................................................***Exception: SegFault  1.46 sec
[   RUN    ] register_half_copy_op
[ COMPLETE ] register_half_copy_op
[   RUN    ] half_copy_custom_op_test
WARNING: MIGraphX built with MLIR but it is not enabled. Please set the env var MIGRAPHX_ENABLE_MLIR to use MLIR kernel generator.
WARNING: MIGraphX built with MLIR but it is not enabled. Please set the env var MIGRAPHX_ENABLE_MLIR to use MLIR kernel generator.

298/328 Test #309: test_api_gpu ..............................................................Subprocess aborted***Exception:   1.66 sec
[   RUN    ] load_and_run
WARNING: MIGraphX built with MLIR but it is not enabled. Please set the env var MIGRAPHX_ENABLE_MLIR to use MLIR kernel generator.
WARNING: MIGraphX built with MLIR but it is not enabled. Please set the env var MIGRAPHX_ENABLE_MLIR to use MLIR kernel generator.

MIGraphX Error: /home/jenkins/workspace/AMDMIGraphX_PR-2323/src/targets/gpu/include/migraphx/gpu/context.hpp:76: create_stream: Failed to allocate stream
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to call function

**Comment by causten** [comment]
And now it passes.

**Pull request merged**
