### PR TITLE
Update protobuf version

### PR DESCRIPTION
**Pull request by kahmed10**
Fixes issue on clang_release build which calls into the onnx runtime test runner.

### CODE REVIEW

**Comment by kahmed10** [comment]
> In requirements.txt it specifically points to protobuf 3.11.0. Could you just change it to 3.20.0 there?

Trying that now.

**Comment by pfultz2** [comment]
We should still pin the protobuf version for python.

**Comment by kahmed10** [comment]
> We should still pin the protobuf version for python to match whatever version we use in requirements.txt.

Updated

**Comment by kahmed10** [comment]
Looks like there's an issue with the newer version of protobuf when building with MIGraphX, so for now I am keeping it as is. We can resolve that issue in a different PR.

**Review by pfultz2 — APPROVED** [review]

**Review by causten — APPROVED** [review]

**Pull request merged**
