### PR TITLE
File ext rename

### PR DESCRIPTION
**Pull request by CharlieL7**
Changed MessagePack file extensions to mxr.

The yolov4 example using Python notebooks looks for a .msgpack extension. Not sure if those should be changed.

### CODE REVIEW

**Comment by kahmed10** [comment]
> Changed MessagePack file extensions to mxr.
> 
> The yolov4 example using Python notebooks looks for a .msgpack extension. Not sure if those should be changed.

Yes please rename them and any other files which are using different extensions.

**Comment by CharlieL7** [comment]
> > The yolov4 example using Python notebooks looks for a .msgpack extension. Not sure if those should be changed.
> 
> Yes please rename them and any other files which are using different extensions.

Made the edits.

**Review by turneram — APPROVED** [review]

**Comment by kahmed10** [comment]
I think there's one more place that needs changing:
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/test/serialize_program.cpp#L51
The .dat extension should be changed here.

**Comment by CharlieL7** [comment]
> I think there's one more place that needs changing: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/develop/test/serialize_program.cpp#L51 The .dat extension should be changed here.

Made changes to ".dat" extensions. 

It's not clear to me if the "msgpack" format and default file format are different or the same. They are handled differently in the parse_load_save.cpp example.

**Review by kahmed10 — APPROVED** [review]

**Pull request merged**
