### PR TITLE
Changes for LessOrEqual operator

### PR DESCRIPTION
**Pull request by cagery**
This PR implements LessOrEqual operator, and fixes issue #722.

- Ref and GPU are implemented.
- Compilation and tests pass.
```
100% tests passed, 0 tests failed out of 282
```

### CODE REVIEW

**Review by scxiao — COMMENTED** [review]
I would prefer this operator to be implementation with the combination of less, or, and equal as
result = (a < b) or (a == b)
In this way, we do not need to implement the kernel, which can reduce our build time in some degree. In addition, it will help for the graph optimization since we have less operations to handle.

**Comment by kahmed10** [comment]
It might be easier to implement it as y = not(greater(x))

**Comment by pfultz2** [comment]
Actually, it could be implemented as `not(less(y, x))` by just flipping the inputs.

**Comment by cagery** [comment]
Closed this branch as the changes here are unnecessary. Working on another branch.

**Pull request closed without merging**
