### PR TITLE
Update name of github action script

### PR DESCRIPTION
**Pull request by TedThemistokleous**
Add space so the name updates for MIGraphX Sync to onnxruntime in Actions

### CODE REVIEW

**Comment by umangyadav** [comment]
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/actions/workflows/sync-onnxrt-main.yaml 

We should also find out why it runs on branches/ PRs.

**Review by umangyadav — DISMISSED** [review]

**Comment by umangyadav** [comment]
> 

This needs to get resolved. 
Also CI is complaining that line 7 is invalid. 
YML file needs to be updated to not use `::set-output`.

**Comment by umangyadav** [comment]
> https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/actions/workflows/sync-onnxrt-main.yaml
> 
> We should also find out why it runs on branches/ PRs.

This needs to get resolved.

**Comment by TedThemistokleous** [comment]
> > 
> 
> This needs to get resolved. Also CI is complaining that line 7 is invalid. YML file needs to be updated to not use `::set-output`.

This already doesn't use ::set-output



> > https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/actions/workflows/sync-onnxrt-main.yaml
> > We should also find out why it runs on branches/ PRs.
> 
> This needs to get resolved.

This should just trigger off cron

**Comment by umangyadav** [comment]
> This already doesn't use ::set-output

 Right. Some of the branches are using older versions of .yml file. that's why i saw that.

**Review by umangyadav — APPROVED** [review]

**Comment by TedThemistokleous** [comment]
> > This already doesn't use ::set-output
> 
> Right. Some of the branches are using older versions of .yml file. that's why i saw that.

Oh, I'll check actions. Maybe I need to prune /update some older branches then.

**Review by causten — APPROVED** [review]

**Pull request merged**
