### PR TITLE
Fix dual literal gather

### PR DESCRIPTION
**Pull request by TedThemistokleous**
Fixes issue with dual literal gather inputs by skipping adding extra converts for the gather operator and its literal inputs

### CODE REVIEW

**Comment by pfultz2** [comment]
Why do we need to skip gather?

**Comment by TedThemistokleous** [comment]
> Why do we need to skip gather?

This was causing us to create a bunch of converts to float that weren't being converted back correctly when the gather op gets folded into the resulting literal.

**Comment by TedThemistokleous** [comment]
Here's the log that this is supposed to fix when running with debug build and backtrace.

[debug_gather_literals.log](https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/files/10984143/debug_gather_literals.log)

**Comment by TedThemistokleous** [comment]
Tested and verified the testcase thats failing used here, and closing this ticket out as PR #1626 solves the issue without skipping over things like in this PR. Pushed test case from this PR into #1626  to maintain coverage

**Pull request closed without merging**
