### PR TITLE
Updates for module name

### PR DESCRIPTION
**Pull request by pfultz2**
This refactors the handling of module names:

- Move name to the impl class
- Set the module name during construction
- Set the main's module name to "main"
- Add tests

### CODE REVIEW

**Review by scxiao — APPROVED** [review]

**Comment by scxiao** [comment]
Looks like all builds passed, but it does not display correctly here.

**Comment by mvermeulen** [comment]
The ONNX seems to be left hanging again.  Same behavior as after previous merge from develop.

**Comment by scxiao** [comment]
> The ONNX seems to be left hanging again. Same behavior as after previous merge from develop. 

One other error message I saw was:
```
[   RUN    ] load_and_run
Memory access fault by GPU node-2 (Agent handle: 0x1dfc130) on address 0x7f4276400000. Reason: Unknown.
```
I just restarted the build to see.

**Comment by scxiao** [comment]
Passed this time and can be merged now.

**Pull request merged**
