### PR TITLE
Change attributes names to be more consistent and reflect better meaning

### LINKED ISSUE #786: refine attribute name in a few operators
We have a few operators "broadcast", "reshape", "multibroadcast" that have an output dims attribute, but each of them use a different name. We can change to use the same name "out_dims" or "out_lens" for all of them. 

The "transpose" operator has an attribute permutation, but we use a name "dims", we can change it to the name "perm" to better reflect the meaning...

### PR DESCRIPTION
**Pull request by umangyadav**
Fixes #786 

Changes 

broadcast operator's attribute name "dims" to "out_lens"
multibroadcast operators' attribute name "output_lens" to "out_lens"
~~reshape op's attribute name "dims" to "out_lens"~~
transpose op's attribute name "dims" to ~~"perm"~~ to "permutation"

### CODE REVIEW

**Comment by pfultz2** [comment]
> transpose op's attribute name "dims" to "perm"

I think it would be better to use `permutation` instead of just `perm`.

**Comment by umangyadav** [comment]
> > transpose op's attribute name "dims" to "perm"
> 
> I think it would be better to use `permutation` instead of just `perm`.

Done. Changed it to "permutation"

**Review by scxiao — APPROVED** [review]

**Comment by pfultz2** [comment]
> reshape op's attribute name "dims" to "out_lens"

I dont think this should be renamed. Dims is different than the out_lens, since you can have `-1` or `0`.

**Comment by umangyadav** [comment]
> > reshape op's attribute name "dims" to "out_lens"
> 
> I dont think this should be renamed. Dims is different than the out_lens, since you can have `-1` or `0`.

Agree.  I can drop that commit.

**Review by pfultz2 — APPROVED** [review]

**Pull request merged**
