### PR TITLE
Add use of implicit deps inside sorting function

### PR DESCRIPTION
**Pull request by umangyadav**
Without this fix sorting produces the following result for the test case inside `module_test.cpp`.  notice that "@return" is placed before parameters and other instructions inside main module. Also program itself is invalid. 

```
module: "main"
cond = @param:cond -> bool_type, {1}, {0}, target_id=0
@1 = if(cond), [If_5_if, If_5_else] -> [float_type, {2, 3}, {3, 1}, float_type, {3, 3}, {3, 1}], target_id=0
@2 = get_tuple_elem[index=0](@1) -> float_type, {2, 3}, {3, 1}, target_id=0
@3 = @return(@2), target_id=0
y2 = @param:y2 -> float_type, {3, 3}, {3, 1}, target_id=0
x2 = @param:x2 -> float_type, {2, 3}, {3, 1}, target_id=0
x1 = @param:x1 -> float_type, {2, 3}, {3, 1}, target_id=0
@7 = @literal{8, 7, 6, 5, 4, 3, 2, 1, 0} -> float_type, {3, 3}, {3, 1}, target_id=0
@8 = @literal{1, 2, 3, 4, 5, 6} -> float_type, {2, 3}, {3, 1}, target_id=0
@9 = get_tuple_elem[index=0](?) -> float_type, {2, 3}, {3, 1}, target_id=0

module: "If_5_if"
If_5_if:@0 = @literal{8, 7, 6, 5, 4, 3, 2, 1, 0} -> float_type, {3, 3}, {3, 1}, target_id=0
If_5_if:@1 = add(x1,@8) -> float_type, {2, 3}, {3, 1}, target_id=0
If_5_if:@2 = @return(If_5_if:@1,If_5_if:@0), target_id=0

module: "If_5_else"
If_5_else:@0 = @literal{8, 7, 6, 5, 4, 3, 2, 1, 0} -> float_type, {3, 3}, {3, 1}, target_id=0
If_5_else:@1 = @return(@9,If_5_else:@0), target_id=0
If_5_else:@2 = if(cond), [If_6_if, If_6_else] -> [float_type, {2, 3}, {3, 1}, float_type, {3, 3}, {3, 1}], target_id=0

module: "If_6_if"
If_6_if:@0 = @literal{8, 7, 6, 5, 4, 3, 2, 1, 0} -> float_type, {3, 3}, {3, 1}, target_id=0
If_6_if:@1 = add(x2,@8) -> float_type, {2, 3}, {3, 1}, target_id=0
If_6_if:@2 = @return(If_6_if:@1,If_6_if:@0), target_id=0

module: "If_6_else"
If_6_else:@0 = mul(y2,@7) -> float_type, {3, 3}, {3, 1}, target_id=0
If_6_else:@1 = @literal{1, 2, 3, 4, 5, 6} -> float_type, {2, 3}, {3, 1}, target_id=0
If_6_else:@2 = @return(If_6_else:@1,If_6_else:@0), target_id=0

```

Sorting is useful for creating multitarget root modules.

### CODE REVIEW

**Review by TedThemistokleous — APPROVED** [review]

**Comment by TedThemistokleous** [comment]
Do we know how much extra time this adds for compile then? Not blocking but more curious if we could leverage this since we're always putting return at the end now.

**Comment by umangyadav** [comment]
> Do we know how much extra time this adds for compile then? 

I don't see "sort" being used other than tests for now.  I may use it for multi-target compilation.

> we're always putting return at the end now.

return should be at the end by design.

**Review by CharlieL7 — COMMENTED** [review]
How does  a call like this `std::distance(main_module_instruction, sub_module_instruction)` work and what would be the distance?

**Comment by umangyadav** [comment]
> How does a call like this `std::distance(main_module_instruction, sub_module_instruction)` work and what would be the distance?

https://en.cppreference.com/w/cpp/iterator/distance

If InputIt is not [LegacyRandomAccessIterator](https://en.cppreference.com/w/cpp/named_req/RandomAccessIterator), the behavior is undefined if last is not [reachable](https://en.cppreference.com/w/cpp/iterator#Ranges) from first.

If InputIt is [LegacyRandomAccessIterator](https://en.cppreference.com/w/cpp/named_req/RandomAccessIterator), the behavior is undefined if first and last are neither reachable from each other.

**Review by CharlieL7 — APPROVED** [review]
LGTM

**Pull request merged**
